### PR TITLE
Added PropTypes

### PR DESCRIPTION
**Pull request by SalemC**
Added type-checking for the props passed to the component.

### CODE REVIEW

**Comment by jakewtaylor** [comment]
Thanks!

However, this is going to break because you haven't added the PropTypes dependencies.

Could you do a `yarn add prop-types -P` and then commit them up?

**Comment by SalemC** [comment]
Done!

**Comment by jakewtaylor** [comment]
I'm not sure why exactly, but this doesn't seem to do anything. I just tried it in a project of mine, intentionally passed it some incorrect props, but got no prop warnings, only normal errors that you'd expect because the data isn't as expected. Any ideas?

**Comment by SalemC** [comment]
Hmm, maybe it was because propTypes didn't require the props? - Just added requiring

**Comment by jakewtaylor** [comment]
Maybe. Sorry, I told you to add the prop-types as a peer dependency but that doesn't automatically install it, can you add it as a normal dependency instead and I'll try that?

**Comment by jakewtaylor** [comment]
Okay, thanks. Not sure why I'm not seeing the prop type warnings because this is right as far as I can tell, so I'm just going to merge it.

**Comment by SalemC** [comment]
Yeah, weird.. I updated package.json to include prop-types as a regular dependency.

**Comment by jakewtaylor** [comment]
If you get a chance to install it and test it, could you let me know if the prop types are working for you? That would be great, thanks!

**Pull request merged**
